version: '3'

services:

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    restart: always
    volumes:
      - ~/mnt/hdd/config/jackett:/config
      - ~/mnt/hdd/downloads:/downloads
      - /etc/localtime:/etc/localtime:ro
    environment:
      PGID: 1000
      PUID: 1000
    ports:
      - 9117:9117

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: always
    volumes: 
      - ~/mnt/hdd/config/sonarr:/config
      - ~/mnt/hdd/tvshows:/tv
      - ~/mnt/hdd/downloads:/downloads
      - /etc/localtime:/etc/localtime:ro
    environment: 
      TZ: Europe/Budapest
      PGID: 1000
      PUID: 1000
    network_mode: host
    ports:
      - 8989:8989

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: always
    volumes:
      - ~/mnt/hdd/config/radarr:/config
      - ~/mnt/hdd/movies:/movies
      - ~/mnt/hdd/downloads:/downloads
      - /etc/localtime:/etc/localtime:ro
    environment: 
      TZ: Europe/Budapest
      PGID: 1000
      PUID: 1000
    network_mode: host
    ports:
      - 7878:7878

  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    restart: always
    volumes: 
      - ~/mnt/hdd/config/lidarr:/config
      - ~/mnt/hdd/downloads:/downloads
      - ~/mnt/hdd/music:/music
    environment: 
      PGID: 1000
      PUID: 1000
    network_mode: host
    ports:
      - 8686:8686

  deluge:
    image: linuxserver/deluge
    container_name: deluge
    restart: always
    volumes:
      - ~/mnt/hdd/config/deluge:/config
      - ~/mnt/hdd/downloads:/downloads
    environment: 
      TZ: Europe/Budapest
      UMASK_SET: 022
      PGID: 1000
      PUID: 1000
    network_mode: host
    ports:
      - 8112:8112
      - 58846:58846
  
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    volumes:
      - ~/mnt/hdd/config/nginx/sites-enabled:/etc/nginx/sites-enabled
    network_mode: host
    ports:
      - 80:80
      - 443:443

  plex:
    image: linuxserver/plex
    container_name: plex
    restart: always
    environment: 
      TZ: Europe/Budapest
      PGID: 1000
      PUID: 1000
    volumes:
      - /mnt/hdd/config/plex:/config
      - /mnt/hdd/tvshows:/data/tvshows
      - /mnt/hdd/movies:/data/movies
      - /mnt/hdd/transcode:/transcode
    network_mode: host
    ports:
      - 32400:32400